export const CLEANUP_PROFILE = 'CLEANUP_PROFILE'

export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE'

export const FETCH_USER_PROFILE_REQUEST = 'FETCH_USER_PROFILE_REQUEST'
export const FETCH_USER_PROFILE_SUCCESS = 'FETCH_USER_PROFILE_SUCCESS'
export const FETCH_USER_PROFILE_FAILURE = 'FETCH_USER_PROFILE_FAILURE'

export const FETCH_USER_PROFILE_COMMENTS_REQUEST =
  'FETCH_USER_PROFILE_COMMENTS_REQUEST'
export const FETCH_USER_PROFILE_COMMENTS_SUCCESS =
  'FETCH_USER_PROFILE_COMMENTS_SUCCESS'
export const FETCH_USER_PROFILE_COMMENTS_FAILURE =
  'FETCH_USER_PROFILE_COMMENTS_FAILURE'

export const FETCH_USER_PROFILE_IMAGE_LIKES_REQUEST =
  'FETCH_USER_PROFILE_IMAGE_LIKES_REQUEST'
export const FETCH_USER_PROFILE_IMAGE_LIKES_SUCCESS =
  'FETCH_USER_PROFILE_IMAGE_LIKES_SUCCESS'
export const FETCH_USER_PROFILE_IMAGE_LIKES_FAILURE =
  'FETCH_USER_PROFILE_IMAGE_LIKES_FAILURE'

export const FETCH_USER_PROFILE_IMAGES_REQUEST =
  'FETCH_USER_PROFILE_IMAGES_REQUEST'
export const FETCH_USER_PROFILE_IMAGES_SUCCESS =
  'FETCH_USER_PROFILE_IMAGES_SUCCESS'
export const FETCH_USER_PROFILE_IMAGES_FAILURE =
  'FETCH_USER_PROFILE_IMAGES_FAILURE'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

export const POST_COMMENT_REQUEST = 'POST_COMMENT_REQUEST'
export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS'
export const POST_COMMENT_FAILURE = 'POST_COMMENT_FAILURE'

export const POST_IMAGE_REQUEST = 'POST_IMAGE_REQUEST'
export const POST_IMAGE_SUCCESS = 'POST_IMAGE_SUCCESS'
export const POST_IMAGE_FAILURE = 'POST_IMAGE_FAILURE'

export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILURE = 'REGISTER_FAILURE'
